# Generated by Django 3.1.5 on 2021-03-08 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('favoriteId', models.AutoField(primary_key=True, serialize=False)),
                ('storeId', models.ManyToManyField(to='store.Store')),
                ('userId', models.ManyToManyField(to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(null=True)),
                ('userComment', models.TextField(null=True)),
                ('commentStatus', models.IntegerField(default=0)),
                ('storeId', models.ManyToManyField(to='store.Store')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
        ),
    ]
