# Generated by Django 3.1.5 on 2021-03-08 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('pictureId', models.AutoField(primary_key=True, serialize=False)),
                ('picture_url', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UserAdministration',
            fields=[
                ('userAdministrationId', models.AutoField(primary_key=True, serialize=False)),
                ('creationDate', models.DateField(auto_now_add=True)),
                ('creationStatus', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('lastConnectionDate', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(default='Anonymous', max_length=100)),
                ('birthDate', models.DateField(null=True)),
                ('pictureId', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.picture')),
                ('userAdministrationId', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='user.useradministration')),
            ],
        ),
    ]
