# Generated by Django 3.1.5 on 2021-03-08 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDescription',
            fields=[
                ('activityId', models.AutoField(primary_key=True, serialize=False)),
                ('activityName', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['activityId', 'activityName'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('countryCodeId', models.AutoField(primary_key=True, serialize=False)),
                ('countryName', models.CharField(default='', max_length=70)),
            ],
            options={
                'ordering': ['countryCodeId', 'countryName'],
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pictureId', models.IntegerField(default='0')),
                ('picture_url', models.CharField(default='', max_length=100)),
            ],
            options={
                'ordering': ['id', 'pictureId', 'picture_url'],
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('storeName', models.CharField(default='', max_length=100)),
                ('storeId', models.IntegerField(default=0)),
                ('streetAvenue', models.CharField(max_length=200, null=True)),
                ('postalCode', models.CharField(max_length=20, null=True)),
                ('website', models.CharField(max_length=100, null=True)),
                ('storeStatus', models.IntegerField(default=0)),
                ('openingTimes', models.CharField(max_length=200, null=True)),
                ('profilePicture', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='store.picture')),
                ('userAdministrationId', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.useradministration')),
            ],
            options={
                'ordering': ['id', 'storeName', 'storeId', 'streetAvenue', 'postalCode', 'website', 'storeStatus', 'openingTimes', 'profilePicture'],
            },
        ),
        migrations.CreateModel(
            name='StoreActivity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('activityName', models.ManyToManyField(to='store.ActivityDescription')),
                ('storeId', models.ManyToManyField(to='store.Store')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityId', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(default='', max_length=100)),
                ('countryCodeId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.country')),
            ],
            options={
                'ordering': ['cityId', 'countryCodeId', 'cityName'],
            },
        ),
    ]
